### ISSUE TITLE
Error when syncing keys to server using fresh install and seeds

### ISSUE THREAD

**Issue by pacoorozco** [pacoorozco/ssham#231]
**Describe the bug**
After installing the aplication and using the default information created by the seed command, the `php artisan ssham:send` command produces an error.

**To Reproduce**
1. Install the application and load the sample data, follow the README instructions.
2. Execute `php artisan ssham:send`
3. See error
```
docker-compose exec app php artisan ssham:send
Hosts to be updated: 1
Updating key for admin@ssh-server

   ArgumentCountError 

  Too few arguments to function App\Events\HostKeysUpdated::__construct(), 0 passed in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php on line 14 and exactly 1 expected

  at app/Events/HostKeysUpdated.php:19
     15▕     {
     16▕         return $this->host;
     17▕     }
     18▕ 
  ➜  19▕     public function __construct(Host $host)
     20▕     {
     21▕         $this->host = $host;
     22▕     }
     23▕ }

      +1 vendor frames 
  2   app/Jobs/UpdateServer.php:56
      App\Events\HostKeysUpdated::dispatch()

      +21 vendor frames 
  24  app/Console/Commands/SendKeysToHosts.php:63
      App\Jobs\UpdateServer::dispatch(Object(App\Models\Host))
```

**Expected behavior**
Keys should synced 

**Desktop (please complete the following information):**
 - OS: kUbuntu 21.04
 - Browser Firefox
 - Version 0.14.2

**Additional context**
Using the provided `docker-compose` environment

**Comment by pacoorozco** [comment]
It's working in the **v0.14.5**
